use_frameworks!

target 'BetteRedditKit_Example' do
  pod 'BetteRedditKit', :path => '../'

  target 'BetteRedditKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
